create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  user_email text,
  prompt text not null,
  reply text not null,
  created_at timestamptz not null default now()
);

alter table public.chat_messages enable row level security;

create policy "Users can read own messages"
on public.chat_messages
for select
using (auth.uid() = user_id);

create policy "Service role can write messages"
on public.chat_messages
for insert
with check (true);
